// src/constants/permissions.ts
export const PERMISSIONS = {
    DASHBOARD_VIEW: "DASHBOARD_VIEW",

    /* =====================
     * Acquisition
     * ===================== */
    ACQUISITION_VIEW: "ACQUISITION_VIEW",
    ACQUISITION_CREATE: "ACQUISITION_CREATE",
    ACQUISITION_UPDATE: "ACQUISITION_UPDATE",
    ACQUISITION_DELETE: "ACQUISITION_DELETE",
    ACQUISITION_APPROVE: "ACQUISITION_APPROVE",

    ORDER_VIEW: "ORDER_VIEW",
    ORDER_CREATE: "ORDER_CREATE",
    ORDER_UPDATE: "ORDER_UPDATE",
    ORDER_DELETE: "ORDER_DELETE",
    ORDER_APPROVE: "ORDER_APPROVE",

    PRODUCT_VIEW: "PRODUCT_VIEW",
    PRODUCT_CREATE: "PRODUCT_CREATE",
    PRODUCT_UPDATE: "PRODUCT_UPDATE",
    PRODUCT_DELETE: "PRODUCT_DELETE",
    PRODUCT_COST_VIEW: "PRODUCT_COST_VIEW",
    PRODUCT_PRICE_EDIT: "PRODUCT_PRICE_EDIT",

    SHIPMENT_VIEW: "SHIPMENT_VIEW",
    SHIPMENT_CREATE: "SHIPMENT_CREATE",
    SHIPMENT_UPDATE: "SHIPMENT_UPDATE",
    SHIPMENT_DELETE: "SHIPMENT_DELETE",
    SHIPMENT_APPROVE: "SHIPMENT_APPROVE",

    SERVICE_VIEW: "SERVICE_VIEW",
    SERVICE_CREATE: "SERVICE_CREATE",
    SERVICE_UPDATE: "SERVICE_UPDATE",
    SERVICE_DELETE: "SERVICE_DELETE",

    USER_VIEW: "USER_VIEW",
    USER_CREATE: "USER_CREATE",
    USER_UPDATE: "USER_UPDATE",
    USER_DELETE: "USER_DELETE",
    USER_MANAGE: "USER_MANAGE",

    CUSTOMER_VIEW: "CUSTOMER_VIEW",
    CUSTOMER_CREATE: "CUSTOMER_CREATE",
    CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
    CUSTOMER_DELETE: "CUSTOMER_DELETE",

    INVOICE_VIEW: "INVOICE_VIEW",
    INVOICE_CREATE: "INVOICE_CREATE",
    INVOICE_UPDATE: "INVOICE_UPDATE",
    INVOICE_DELETE: "INVOICE_DELETE",


    PAYMENT_VIEW: "PAYMENT_VIEW",
    PAYMENT_CREATE: "PAYMENT_CREATE",
    PAYMENT_UPDATE: "PAYMENT_UPDATE",
    PAYMENT_DELETE: "PAYMENT_DELETE",

    REPORT_VIEW: "REPORT_VIEW",




} as const;
