import * as z from 'zod';

// prettier-ignore
export const technicalAssessmentsInputSchema = z.object({
    id: z.string(),
    serviceRequestId: z.string(),
    machineType: z.string().optional().nullable(),
    movementStatus: z.string().optional().nullable(),
    beforeRate: z.string().optional().nullable(),
    beforeAmp: z.string().optional().nullable(),
    beforeErr: z.string().optional().nullable(),
    afterRate: z.string().optional().nullable(),
    afterAmp: z.string().optional().nullable(),
    afterErr: z.string().optional().nullable(),
    appearanceScore: z.number().int(),
    caseScore: z.number().int(),
    glassScore: z.number().int(),
    dialScore: z.number().int(),
    caseIssues: z.unknown().optional().nullable(),
    glassIssues: z.unknown().optional().nullable(),
    dialIssues: z.unknown().optional().nullable(),
    caseManualDeduction: z.number().int(),
    glassManualDeduction: z.number().int(),
    dialManualDeduction: z.number().int(),
    caseNote: z.string().optional().nullable(),
    glassNote: z.string().optional().nullable(),
    dialNote: z.string().optional().nullable(),
    crownStatus: z.string().optional().nullable(),
    crownAction: z.string().optional().nullable(),
    crownExecution: z.string().optional().nullable(),
    crownVendorId: z.string().optional().nullable(),
    crownPartId: z.string().optional().nullable(),
    crownCost: z.number().int(),
    crownNote: z.string().optional().nullable(),
    movementCost: z.number().int(),
    crownCostTotal: z.number().int(),
    cosmeticProposalCost: z.number().int(),
    totalCost: z.number().int(),
    conclusion: z.string().optional().nullable(),
    createdAt: z.date(),
    updatedAt: z.date(),
    approvalRequests: z.array(z.unknown())
}).strict();

export type technicalAssessmentsInputType = z.infer<typeof technicalAssessmentsInputSchema>;
