import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TechnicalAssessmentOrderByWithRelationInputObjectSchema as TechnicalAssessmentOrderByWithRelationInputObjectSchema } from './objects/TechnicalAssessmentOrderByWithRelationInput.schema';
import { TechnicalAssessmentWhereInputObjectSchema as TechnicalAssessmentWhereInputObjectSchema } from './objects/TechnicalAssessmentWhereInput.schema';
import { TechnicalAssessmentWhereUniqueInputObjectSchema as TechnicalAssessmentWhereUniqueInputObjectSchema } from './objects/TechnicalAssessmentWhereUniqueInput.schema';
import { TechnicalAssessmentCountAggregateInputObjectSchema as TechnicalAssessmentCountAggregateInputObjectSchema } from './objects/TechnicalAssessmentCountAggregateInput.schema';
import { TechnicalAssessmentMinAggregateInputObjectSchema as TechnicalAssessmentMinAggregateInputObjectSchema } from './objects/TechnicalAssessmentMinAggregateInput.schema';
import { TechnicalAssessmentMaxAggregateInputObjectSchema as TechnicalAssessmentMaxAggregateInputObjectSchema } from './objects/TechnicalAssessmentMaxAggregateInput.schema';
import { TechnicalAssessmentAvgAggregateInputObjectSchema as TechnicalAssessmentAvgAggregateInputObjectSchema } from './objects/TechnicalAssessmentAvgAggregateInput.schema';
import { TechnicalAssessmentSumAggregateInputObjectSchema as TechnicalAssessmentSumAggregateInputObjectSchema } from './objects/TechnicalAssessmentSumAggregateInput.schema';

export const TechnicalAssessmentAggregateSchema: z.ZodType<Prisma.TechnicalAssessmentAggregateArgs> = z.object({ orderBy: z.union([TechnicalAssessmentOrderByWithRelationInputObjectSchema, TechnicalAssessmentOrderByWithRelationInputObjectSchema.array()]).optional(), where: TechnicalAssessmentWhereInputObjectSchema.optional(), cursor: TechnicalAssessmentWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalAssessmentCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAssessmentMinAggregateInputObjectSchema.optional(), _max: TechnicalAssessmentMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAssessmentAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAssessmentSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TechnicalAssessmentAggregateArgs>;

export const TechnicalAssessmentAggregateZodSchema = z.object({ orderBy: z.union([TechnicalAssessmentOrderByWithRelationInputObjectSchema, TechnicalAssessmentOrderByWithRelationInputObjectSchema.array()]).optional(), where: TechnicalAssessmentWhereInputObjectSchema.optional(), cursor: TechnicalAssessmentWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalAssessmentCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAssessmentMinAggregateInputObjectSchema.optional(), _max: TechnicalAssessmentMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAssessmentAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAssessmentSumAggregateInputObjectSchema.optional() }).strict();