import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema as technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema } from './objects/technicalAppearanceIssueCatalogOrderByWithRelationInput.schema';
import { technicalAppearanceIssueCatalogWhereInputObjectSchema as technicalAppearanceIssueCatalogWhereInputObjectSchema } from './objects/technicalAppearanceIssueCatalogWhereInput.schema';
import { technicalAppearanceIssueCatalogWhereUniqueInputObjectSchema as technicalAppearanceIssueCatalogWhereUniqueInputObjectSchema } from './objects/technicalAppearanceIssueCatalogWhereUniqueInput.schema';
import { TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogCountAggregateInput.schema';
import { TechnicalAppearanceIssueCatalogMinAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogMinAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogMinAggregateInput.schema';
import { TechnicalAppearanceIssueCatalogMaxAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogMaxAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogMaxAggregateInput.schema';
import { TechnicalAppearanceIssueCatalogAvgAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogAvgAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogAvgAggregateInput.schema';
import { TechnicalAppearanceIssueCatalogSumAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogSumAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogSumAggregateInput.schema';

export const technicalAppearanceIssueCatalogAggregateSchema: z.ZodType<Prisma.technicalAppearanceIssueCatalogAggregateArgs> = z.object({ orderBy: z.union([technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema, technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalAppearanceIssueCatalogWhereInputObjectSchema.optional(), cursor: technicalAppearanceIssueCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAppearanceIssueCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalAppearanceIssueCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAppearanceIssueCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAppearanceIssueCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.technicalAppearanceIssueCatalogAggregateArgs>;

export const technicalAppearanceIssueCatalogAggregateZodSchema = z.object({ orderBy: z.union([technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema, technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalAppearanceIssueCatalogWhereInputObjectSchema.optional(), cursor: technicalAppearanceIssueCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAppearanceIssueCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalAppearanceIssueCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAppearanceIssueCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAppearanceIssueCatalogSumAggregateInputObjectSchema.optional() }).strict();