import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { SupplyCatalogOrderByWithRelationInputObjectSchema as SupplyCatalogOrderByWithRelationInputObjectSchema } from './objects/SupplyCatalogOrderByWithRelationInput.schema';
import { SupplyCatalogWhereInputObjectSchema as SupplyCatalogWhereInputObjectSchema } from './objects/SupplyCatalogWhereInput.schema';
import { SupplyCatalogWhereUniqueInputObjectSchema as SupplyCatalogWhereUniqueInputObjectSchema } from './objects/SupplyCatalogWhereUniqueInput.schema';
import { SupplyCatalogCountAggregateInputObjectSchema as SupplyCatalogCountAggregateInputObjectSchema } from './objects/SupplyCatalogCountAggregateInput.schema';
import { SupplyCatalogMinAggregateInputObjectSchema as SupplyCatalogMinAggregateInputObjectSchema } from './objects/SupplyCatalogMinAggregateInput.schema';
import { SupplyCatalogMaxAggregateInputObjectSchema as SupplyCatalogMaxAggregateInputObjectSchema } from './objects/SupplyCatalogMaxAggregateInput.schema';
import { SupplyCatalogAvgAggregateInputObjectSchema as SupplyCatalogAvgAggregateInputObjectSchema } from './objects/SupplyCatalogAvgAggregateInput.schema';
import { SupplyCatalogSumAggregateInputObjectSchema as SupplyCatalogSumAggregateInputObjectSchema } from './objects/SupplyCatalogSumAggregateInput.schema';

export const SupplyCatalogAggregateSchema: z.ZodType<Prisma.SupplyCatalogAggregateArgs> = z.object({ orderBy: z.union([SupplyCatalogOrderByWithRelationInputObjectSchema, SupplyCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: SupplyCatalogWhereInputObjectSchema.optional(), cursor: SupplyCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), SupplyCatalogCountAggregateInputObjectSchema ]).optional(), _min: SupplyCatalogMinAggregateInputObjectSchema.optional(), _max: SupplyCatalogMaxAggregateInputObjectSchema.optional(), _avg: SupplyCatalogAvgAggregateInputObjectSchema.optional(), _sum: SupplyCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.SupplyCatalogAggregateArgs>;

export const SupplyCatalogAggregateZodSchema = z.object({ orderBy: z.union([SupplyCatalogOrderByWithRelationInputObjectSchema, SupplyCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: SupplyCatalogWhereInputObjectSchema.optional(), cursor: SupplyCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), SupplyCatalogCountAggregateInputObjectSchema ]).optional(), _min: SupplyCatalogMinAggregateInputObjectSchema.optional(), _max: SupplyCatalogMaxAggregateInputObjectSchema.optional(), _avg: SupplyCatalogAvgAggregateInputObjectSchema.optional(), _sum: SupplyCatalogSumAggregateInputObjectSchema.optional() }).strict();