import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalPartCatalogOrderByWithRelationInputObjectSchema as technicalPartCatalogOrderByWithRelationInputObjectSchema } from './objects/technicalPartCatalogOrderByWithRelationInput.schema';
import { technicalPartCatalogWhereInputObjectSchema as technicalPartCatalogWhereInputObjectSchema } from './objects/technicalPartCatalogWhereInput.schema';
import { technicalPartCatalogWhereUniqueInputObjectSchema as technicalPartCatalogWhereUniqueInputObjectSchema } from './objects/technicalPartCatalogWhereUniqueInput.schema';
import { TechnicalPartCatalogCountAggregateInputObjectSchema as TechnicalPartCatalogCountAggregateInputObjectSchema } from './objects/TechnicalPartCatalogCountAggregateInput.schema';
import { TechnicalPartCatalogMinAggregateInputObjectSchema as TechnicalPartCatalogMinAggregateInputObjectSchema } from './objects/TechnicalPartCatalogMinAggregateInput.schema';
import { TechnicalPartCatalogMaxAggregateInputObjectSchema as TechnicalPartCatalogMaxAggregateInputObjectSchema } from './objects/TechnicalPartCatalogMaxAggregateInput.schema';
import { TechnicalPartCatalogAvgAggregateInputObjectSchema as TechnicalPartCatalogAvgAggregateInputObjectSchema } from './objects/TechnicalPartCatalogAvgAggregateInput.schema';
import { TechnicalPartCatalogSumAggregateInputObjectSchema as TechnicalPartCatalogSumAggregateInputObjectSchema } from './objects/TechnicalPartCatalogSumAggregateInput.schema';

export const technicalPartCatalogAggregateSchema: z.ZodType<Prisma.technicalPartCatalogAggregateArgs> = z.object({ orderBy: z.union([technicalPartCatalogOrderByWithRelationInputObjectSchema, technicalPartCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalPartCatalogWhereInputObjectSchema.optional(), cursor: technicalPartCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalPartCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalPartCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalPartCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalPartCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalPartCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.technicalPartCatalogAggregateArgs>;

export const technicalPartCatalogAggregateZodSchema = z.object({ orderBy: z.union([technicalPartCatalogOrderByWithRelationInputObjectSchema, technicalPartCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalPartCatalogWhereInputObjectSchema.optional(), cursor: technicalPartCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalPartCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalPartCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalPartCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalPartCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalPartCatalogSumAggregateInputObjectSchema.optional() }).strict();