import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { system_job_controlOrderByWithRelationInputObjectSchema as system_job_controlOrderByWithRelationInputObjectSchema } from './objects/system_job_controlOrderByWithRelationInput.schema';
import { system_job_controlWhereInputObjectSchema as system_job_controlWhereInputObjectSchema } from './objects/system_job_controlWhereInput.schema';
import { system_job_controlWhereUniqueInputObjectSchema as system_job_controlWhereUniqueInputObjectSchema } from './objects/system_job_controlWhereUniqueInput.schema';
import { System_job_controlCountAggregateInputObjectSchema as System_job_controlCountAggregateInputObjectSchema } from './objects/System_job_controlCountAggregateInput.schema';
import { System_job_controlMinAggregateInputObjectSchema as System_job_controlMinAggregateInputObjectSchema } from './objects/System_job_controlMinAggregateInput.schema';
import { System_job_controlMaxAggregateInputObjectSchema as System_job_controlMaxAggregateInputObjectSchema } from './objects/System_job_controlMaxAggregateInput.schema';
import { System_job_controlAvgAggregateInputObjectSchema as System_job_controlAvgAggregateInputObjectSchema } from './objects/System_job_controlAvgAggregateInput.schema';
import { System_job_controlSumAggregateInputObjectSchema as System_job_controlSumAggregateInputObjectSchema } from './objects/System_job_controlSumAggregateInput.schema';

export const system_job_controlAggregateSchema: z.ZodType<Prisma.System_job_controlAggregateArgs> = z.object({ orderBy: z.union([system_job_controlOrderByWithRelationInputObjectSchema, system_job_controlOrderByWithRelationInputObjectSchema.array()]).optional(), where: system_job_controlWhereInputObjectSchema.optional(), cursor: system_job_controlWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), System_job_controlCountAggregateInputObjectSchema ]).optional(), _min: System_job_controlMinAggregateInputObjectSchema.optional(), _max: System_job_controlMaxAggregateInputObjectSchema.optional(), _avg: System_job_controlAvgAggregateInputObjectSchema.optional(), _sum: System_job_controlSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.System_job_controlAggregateArgs>;

export const system_job_controlAggregateZodSchema = z.object({ orderBy: z.union([system_job_controlOrderByWithRelationInputObjectSchema, system_job_controlOrderByWithRelationInputObjectSchema.array()]).optional(), where: system_job_controlWhereInputObjectSchema.optional(), cursor: system_job_controlWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), System_job_controlCountAggregateInputObjectSchema ]).optional(), _min: System_job_controlMinAggregateInputObjectSchema.optional(), _max: System_job_controlMaxAggregateInputObjectSchema.optional(), _avg: System_job_controlAvgAggregateInputObjectSchema.optional(), _sum: System_job_controlSumAggregateInputObjectSchema.optional() }).strict();