import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MechanicalPartCatalogOrderByWithRelationInputObjectSchema as MechanicalPartCatalogOrderByWithRelationInputObjectSchema } from './objects/MechanicalPartCatalogOrderByWithRelationInput.schema';
import { MechanicalPartCatalogWhereInputObjectSchema as MechanicalPartCatalogWhereInputObjectSchema } from './objects/MechanicalPartCatalogWhereInput.schema';
import { MechanicalPartCatalogWhereUniqueInputObjectSchema as MechanicalPartCatalogWhereUniqueInputObjectSchema } from './objects/MechanicalPartCatalogWhereUniqueInput.schema';
import { MechanicalPartCatalogCountAggregateInputObjectSchema as MechanicalPartCatalogCountAggregateInputObjectSchema } from './objects/MechanicalPartCatalogCountAggregateInput.schema';
import { MechanicalPartCatalogMinAggregateInputObjectSchema as MechanicalPartCatalogMinAggregateInputObjectSchema } from './objects/MechanicalPartCatalogMinAggregateInput.schema';
import { MechanicalPartCatalogMaxAggregateInputObjectSchema as MechanicalPartCatalogMaxAggregateInputObjectSchema } from './objects/MechanicalPartCatalogMaxAggregateInput.schema';
import { MechanicalPartCatalogAvgAggregateInputObjectSchema as MechanicalPartCatalogAvgAggregateInputObjectSchema } from './objects/MechanicalPartCatalogAvgAggregateInput.schema';
import { MechanicalPartCatalogSumAggregateInputObjectSchema as MechanicalPartCatalogSumAggregateInputObjectSchema } from './objects/MechanicalPartCatalogSumAggregateInput.schema';

export const MechanicalPartCatalogAggregateSchema: z.ZodType<Prisma.MechanicalPartCatalogAggregateArgs> = z.object({ orderBy: z.union([MechanicalPartCatalogOrderByWithRelationInputObjectSchema, MechanicalPartCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: MechanicalPartCatalogWhereInputObjectSchema.optional(), cursor: MechanicalPartCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MechanicalPartCatalogCountAggregateInputObjectSchema ]).optional(), _min: MechanicalPartCatalogMinAggregateInputObjectSchema.optional(), _max: MechanicalPartCatalogMaxAggregateInputObjectSchema.optional(), _avg: MechanicalPartCatalogAvgAggregateInputObjectSchema.optional(), _sum: MechanicalPartCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MechanicalPartCatalogAggregateArgs>;

export const MechanicalPartCatalogAggregateZodSchema = z.object({ orderBy: z.union([MechanicalPartCatalogOrderByWithRelationInputObjectSchema, MechanicalPartCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: MechanicalPartCatalogWhereInputObjectSchema.optional(), cursor: MechanicalPartCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MechanicalPartCatalogCountAggregateInputObjectSchema ]).optional(), _min: MechanicalPartCatalogMinAggregateInputObjectSchema.optional(), _max: MechanicalPartCatalogMaxAggregateInputObjectSchema.optional(), _avg: MechanicalPartCatalogAvgAggregateInputObjectSchema.optional(), _sum: MechanicalPartCatalogSumAggregateInputObjectSchema.optional() }).strict();