import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalAssessmentsOrderByWithRelationInputObjectSchema as technicalAssessmentsOrderByWithRelationInputObjectSchema } from './objects/technicalAssessmentsOrderByWithRelationInput.schema';
import { technicalAssessmentsWhereInputObjectSchema as technicalAssessmentsWhereInputObjectSchema } from './objects/technicalAssessmentsWhereInput.schema';
import { technicalAssessmentsWhereUniqueInputObjectSchema as technicalAssessmentsWhereUniqueInputObjectSchema } from './objects/technicalAssessmentsWhereUniqueInput.schema';
import { TechnicalAssessmentsCountAggregateInputObjectSchema as TechnicalAssessmentsCountAggregateInputObjectSchema } from './objects/TechnicalAssessmentsCountAggregateInput.schema';
import { TechnicalAssessmentsMinAggregateInputObjectSchema as TechnicalAssessmentsMinAggregateInputObjectSchema } from './objects/TechnicalAssessmentsMinAggregateInput.schema';
import { TechnicalAssessmentsMaxAggregateInputObjectSchema as TechnicalAssessmentsMaxAggregateInputObjectSchema } from './objects/TechnicalAssessmentsMaxAggregateInput.schema';
import { TechnicalAssessmentsAvgAggregateInputObjectSchema as TechnicalAssessmentsAvgAggregateInputObjectSchema } from './objects/TechnicalAssessmentsAvgAggregateInput.schema';
import { TechnicalAssessmentsSumAggregateInputObjectSchema as TechnicalAssessmentsSumAggregateInputObjectSchema } from './objects/TechnicalAssessmentsSumAggregateInput.schema';

export const technicalAssessmentsAggregateSchema: z.ZodType<Prisma.technicalAssessmentsAggregateArgs> = z.object({ orderBy: z.union([technicalAssessmentsOrderByWithRelationInputObjectSchema, technicalAssessmentsOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalAssessmentsWhereInputObjectSchema.optional(), cursor: technicalAssessmentsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalAssessmentsCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAssessmentsMinAggregateInputObjectSchema.optional(), _max: TechnicalAssessmentsMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAssessmentsAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAssessmentsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.technicalAssessmentsAggregateArgs>;

export const technicalAssessmentsAggregateZodSchema = z.object({ orderBy: z.union([technicalAssessmentsOrderByWithRelationInputObjectSchema, technicalAssessmentsOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalAssessmentsWhereInputObjectSchema.optional(), cursor: technicalAssessmentsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalAssessmentsCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAssessmentsMinAggregateInputObjectSchema.optional(), _max: TechnicalAssessmentsMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAssessmentsAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAssessmentsSumAggregateInputObjectSchema.optional() }).strict();