import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalActionCatalogOrderByWithRelationInputObjectSchema as technicalActionCatalogOrderByWithRelationInputObjectSchema } from './objects/technicalActionCatalogOrderByWithRelationInput.schema';
import { technicalActionCatalogWhereInputObjectSchema as technicalActionCatalogWhereInputObjectSchema } from './objects/technicalActionCatalogWhereInput.schema';
import { technicalActionCatalogWhereUniqueInputObjectSchema as technicalActionCatalogWhereUniqueInputObjectSchema } from './objects/technicalActionCatalogWhereUniqueInput.schema';
import { TechnicalActionCatalogCountAggregateInputObjectSchema as TechnicalActionCatalogCountAggregateInputObjectSchema } from './objects/TechnicalActionCatalogCountAggregateInput.schema';
import { TechnicalActionCatalogMinAggregateInputObjectSchema as TechnicalActionCatalogMinAggregateInputObjectSchema } from './objects/TechnicalActionCatalogMinAggregateInput.schema';
import { TechnicalActionCatalogMaxAggregateInputObjectSchema as TechnicalActionCatalogMaxAggregateInputObjectSchema } from './objects/TechnicalActionCatalogMaxAggregateInput.schema';
import { TechnicalActionCatalogAvgAggregateInputObjectSchema as TechnicalActionCatalogAvgAggregateInputObjectSchema } from './objects/TechnicalActionCatalogAvgAggregateInput.schema';
import { TechnicalActionCatalogSumAggregateInputObjectSchema as TechnicalActionCatalogSumAggregateInputObjectSchema } from './objects/TechnicalActionCatalogSumAggregateInput.schema';

export const technicalActionCatalogAggregateSchema: z.ZodType<Prisma.technicalActionCatalogAggregateArgs> = z.object({ orderBy: z.union([technicalActionCatalogOrderByWithRelationInputObjectSchema, technicalActionCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalActionCatalogWhereInputObjectSchema.optional(), cursor: technicalActionCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalActionCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalActionCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalActionCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalActionCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalActionCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.technicalActionCatalogAggregateArgs>;

export const technicalActionCatalogAggregateZodSchema = z.object({ orderBy: z.union([technicalActionCatalogOrderByWithRelationInputObjectSchema, technicalActionCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalActionCatalogWhereInputObjectSchema.optional(), cursor: technicalActionCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), TechnicalActionCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalActionCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalActionCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalActionCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalActionCatalogSumAggregateInputObjectSchema.optional() }).strict();