import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AcquisitionSpecJobOrderByWithRelationInputObjectSchema as AcquisitionSpecJobOrderByWithRelationInputObjectSchema } from './objects/AcquisitionSpecJobOrderByWithRelationInput.schema';
import { AcquisitionSpecJobWhereInputObjectSchema as AcquisitionSpecJobWhereInputObjectSchema } from './objects/AcquisitionSpecJobWhereInput.schema';
import { AcquisitionSpecJobWhereUniqueInputObjectSchema as AcquisitionSpecJobWhereUniqueInputObjectSchema } from './objects/AcquisitionSpecJobWhereUniqueInput.schema';
import { AcquisitionSpecJobCountAggregateInputObjectSchema as AcquisitionSpecJobCountAggregateInputObjectSchema } from './objects/AcquisitionSpecJobCountAggregateInput.schema';
import { AcquisitionSpecJobMinAggregateInputObjectSchema as AcquisitionSpecJobMinAggregateInputObjectSchema } from './objects/AcquisitionSpecJobMinAggregateInput.schema';
import { AcquisitionSpecJobMaxAggregateInputObjectSchema as AcquisitionSpecJobMaxAggregateInputObjectSchema } from './objects/AcquisitionSpecJobMaxAggregateInput.schema';
import { AcquisitionSpecJobAvgAggregateInputObjectSchema as AcquisitionSpecJobAvgAggregateInputObjectSchema } from './objects/AcquisitionSpecJobAvgAggregateInput.schema';
import { AcquisitionSpecJobSumAggregateInputObjectSchema as AcquisitionSpecJobSumAggregateInputObjectSchema } from './objects/AcquisitionSpecJobSumAggregateInput.schema';

export const AcquisitionSpecJobAggregateSchema: z.ZodType<Prisma.AcquisitionSpecJobAggregateArgs> = z.object({ orderBy: z.union([AcquisitionSpecJobOrderByWithRelationInputObjectSchema, AcquisitionSpecJobOrderByWithRelationInputObjectSchema.array()]).optional(), where: AcquisitionSpecJobWhereInputObjectSchema.optional(), cursor: AcquisitionSpecJobWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AcquisitionSpecJobCountAggregateInputObjectSchema ]).optional(), _min: AcquisitionSpecJobMinAggregateInputObjectSchema.optional(), _max: AcquisitionSpecJobMaxAggregateInputObjectSchema.optional(), _avg: AcquisitionSpecJobAvgAggregateInputObjectSchema.optional(), _sum: AcquisitionSpecJobSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AcquisitionSpecJobAggregateArgs>;

export const AcquisitionSpecJobAggregateZodSchema = z.object({ orderBy: z.union([AcquisitionSpecJobOrderByWithRelationInputObjectSchema, AcquisitionSpecJobOrderByWithRelationInputObjectSchema.array()]).optional(), where: AcquisitionSpecJobWhereInputObjectSchema.optional(), cursor: AcquisitionSpecJobWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AcquisitionSpecJobCountAggregateInputObjectSchema ]).optional(), _min: AcquisitionSpecJobMinAggregateInputObjectSchema.optional(), _max: AcquisitionSpecJobMaxAggregateInputObjectSchema.optional(), _avg: AcquisitionSpecJobAvgAggregateInputObjectSchema.optional(), _sum: AcquisitionSpecJobSumAggregateInputObjectSchema.optional() }).strict();