import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MechanicalPartCatalogOrderByWithRelationInputObjectSchema as MechanicalPartCatalogOrderByWithRelationInputObjectSchema } from './objects/MechanicalPartCatalogOrderByWithRelationInput.schema';
import { MechanicalPartCatalogWhereInputObjectSchema as MechanicalPartCatalogWhereInputObjectSchema } from './objects/MechanicalPartCatalogWhereInput.schema';
import { MechanicalPartCatalogWhereUniqueInputObjectSchema as MechanicalPartCatalogWhereUniqueInputObjectSchema } from './objects/MechanicalPartCatalogWhereUniqueInput.schema';
import { MechanicalPartCatalogCountAggregateInputObjectSchema as MechanicalPartCatalogCountAggregateInputObjectSchema } from './objects/MechanicalPartCatalogCountAggregateInput.schema';

export const MechanicalPartCatalogCountSchema: z.ZodType<Prisma.MechanicalPartCatalogCountArgs> = z.object({ orderBy: z.union([MechanicalPartCatalogOrderByWithRelationInputObjectSchema, MechanicalPartCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: MechanicalPartCatalogWhereInputObjectSchema.optional(), cursor: MechanicalPartCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), MechanicalPartCatalogCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.MechanicalPartCatalogCountArgs>;

export const MechanicalPartCatalogCountZodSchema = z.object({ orderBy: z.union([MechanicalPartCatalogOrderByWithRelationInputObjectSchema, MechanicalPartCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: MechanicalPartCatalogWhereInputObjectSchema.optional(), cursor: MechanicalPartCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), MechanicalPartCatalogCountAggregateInputObjectSchema ]).optional() }).strict();