import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { system_job_controlOrderByWithRelationInputObjectSchema as system_job_controlOrderByWithRelationInputObjectSchema } from './objects/system_job_controlOrderByWithRelationInput.schema';
import { system_job_controlWhereInputObjectSchema as system_job_controlWhereInputObjectSchema } from './objects/system_job_controlWhereInput.schema';
import { system_job_controlWhereUniqueInputObjectSchema as system_job_controlWhereUniqueInputObjectSchema } from './objects/system_job_controlWhereUniqueInput.schema';
import { System_job_controlCountAggregateInputObjectSchema as System_job_controlCountAggregateInputObjectSchema } from './objects/System_job_controlCountAggregateInput.schema';

export const system_job_controlCountSchema: z.ZodType<Prisma.system_job_controlCountArgs> = z.object({ orderBy: z.union([system_job_controlOrderByWithRelationInputObjectSchema, system_job_controlOrderByWithRelationInputObjectSchema.array()]).optional(), where: system_job_controlWhereInputObjectSchema.optional(), cursor: system_job_controlWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), System_job_controlCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.system_job_controlCountArgs>;

export const system_job_controlCountZodSchema = z.object({ orderBy: z.union([system_job_controlOrderByWithRelationInputObjectSchema, system_job_controlOrderByWithRelationInputObjectSchema.array()]).optional(), where: system_job_controlWhereInputObjectSchema.optional(), cursor: system_job_controlWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), System_job_controlCountAggregateInputObjectSchema ]).optional() }).strict();