import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { system_job_run_logOrderByWithRelationInputObjectSchema as system_job_run_logOrderByWithRelationInputObjectSchema } from './objects/system_job_run_logOrderByWithRelationInput.schema';
import { system_job_run_logWhereInputObjectSchema as system_job_run_logWhereInputObjectSchema } from './objects/system_job_run_logWhereInput.schema';
import { system_job_run_logWhereUniqueInputObjectSchema as system_job_run_logWhereUniqueInputObjectSchema } from './objects/system_job_run_logWhereUniqueInput.schema';
import { System_job_run_logCountAggregateInputObjectSchema as System_job_run_logCountAggregateInputObjectSchema } from './objects/System_job_run_logCountAggregateInput.schema';

export const system_job_run_logCountSchema: z.ZodType<Prisma.system_job_run_logCountArgs> = z.object({ orderBy: z.union([system_job_run_logOrderByWithRelationInputObjectSchema, system_job_run_logOrderByWithRelationInputObjectSchema.array()]).optional(), where: system_job_run_logWhereInputObjectSchema.optional(), cursor: system_job_run_logWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), System_job_run_logCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.system_job_run_logCountArgs>;

export const system_job_run_logCountZodSchema = z.object({ orderBy: z.union([system_job_run_logOrderByWithRelationInputObjectSchema, system_job_run_logOrderByWithRelationInputObjectSchema.array()]).optional(), where: system_job_run_logWhereInputObjectSchema.optional(), cursor: system_job_run_logWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), System_job_run_logCountAggregateInputObjectSchema ]).optional() }).strict();