import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AcquisitionSpecJobOrderByWithRelationInputObjectSchema as AcquisitionSpecJobOrderByWithRelationInputObjectSchema } from './objects/AcquisitionSpecJobOrderByWithRelationInput.schema';
import { AcquisitionSpecJobWhereInputObjectSchema as AcquisitionSpecJobWhereInputObjectSchema } from './objects/AcquisitionSpecJobWhereInput.schema';
import { AcquisitionSpecJobWhereUniqueInputObjectSchema as AcquisitionSpecJobWhereUniqueInputObjectSchema } from './objects/AcquisitionSpecJobWhereUniqueInput.schema';
import { AcquisitionSpecJobCountAggregateInputObjectSchema as AcquisitionSpecJobCountAggregateInputObjectSchema } from './objects/AcquisitionSpecJobCountAggregateInput.schema';

export const AcquisitionSpecJobCountSchema: z.ZodType<Prisma.AcquisitionSpecJobCountArgs> = z.object({ orderBy: z.union([AcquisitionSpecJobOrderByWithRelationInputObjectSchema, AcquisitionSpecJobOrderByWithRelationInputObjectSchema.array()]).optional(), where: AcquisitionSpecJobWhereInputObjectSchema.optional(), cursor: AcquisitionSpecJobWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), AcquisitionSpecJobCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.AcquisitionSpecJobCountArgs>;

export const AcquisitionSpecJobCountZodSchema = z.object({ orderBy: z.union([AcquisitionSpecJobOrderByWithRelationInputObjectSchema, AcquisitionSpecJobOrderByWithRelationInputObjectSchema.array()]).optional(), where: AcquisitionSpecJobWhereInputObjectSchema.optional(), cursor: AcquisitionSpecJobWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), AcquisitionSpecJobCountAggregateInputObjectSchema ]).optional() }).strict();