import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalPartCatalogOrderByWithRelationInputObjectSchema as technicalPartCatalogOrderByWithRelationInputObjectSchema } from './objects/technicalPartCatalogOrderByWithRelationInput.schema';
import { technicalPartCatalogWhereInputObjectSchema as technicalPartCatalogWhereInputObjectSchema } from './objects/technicalPartCatalogWhereInput.schema';
import { technicalPartCatalogWhereUniqueInputObjectSchema as technicalPartCatalogWhereUniqueInputObjectSchema } from './objects/technicalPartCatalogWhereUniqueInput.schema';
import { TechnicalPartCatalogCountAggregateInputObjectSchema as TechnicalPartCatalogCountAggregateInputObjectSchema } from './objects/TechnicalPartCatalogCountAggregateInput.schema';

export const technicalPartCatalogCountSchema: z.ZodType<Prisma.technicalPartCatalogCountArgs> = z.object({ orderBy: z.union([technicalPartCatalogOrderByWithRelationInputObjectSchema, technicalPartCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalPartCatalogWhereInputObjectSchema.optional(), cursor: technicalPartCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), TechnicalPartCatalogCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.technicalPartCatalogCountArgs>;

export const technicalPartCatalogCountZodSchema = z.object({ orderBy: z.union([technicalPartCatalogOrderByWithRelationInputObjectSchema, technicalPartCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalPartCatalogWhereInputObjectSchema.optional(), cursor: technicalPartCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), TechnicalPartCatalogCountAggregateInputObjectSchema ]).optional() }).strict();