import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema as technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema } from './objects/technicalAppearanceIssueCatalogOrderByWithRelationInput.schema';
import { technicalAppearanceIssueCatalogWhereInputObjectSchema as technicalAppearanceIssueCatalogWhereInputObjectSchema } from './objects/technicalAppearanceIssueCatalogWhereInput.schema';
import { technicalAppearanceIssueCatalogWhereUniqueInputObjectSchema as technicalAppearanceIssueCatalogWhereUniqueInputObjectSchema } from './objects/technicalAppearanceIssueCatalogWhereUniqueInput.schema';
import { TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogCountAggregateInput.schema';

export const technicalAppearanceIssueCatalogCountSchema: z.ZodType<Prisma.technicalAppearanceIssueCatalogCountArgs> = z.object({ orderBy: z.union([technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema, technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalAppearanceIssueCatalogWhereInputObjectSchema.optional(), cursor: technicalAppearanceIssueCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.technicalAppearanceIssueCatalogCountArgs>;

export const technicalAppearanceIssueCatalogCountZodSchema = z.object({ orderBy: z.union([technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema, technicalAppearanceIssueCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalAppearanceIssueCatalogWhereInputObjectSchema.optional(), cursor: technicalAppearanceIssueCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema ]).optional() }).strict();