import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalActionCatalogOrderByWithRelationInputObjectSchema as technicalActionCatalogOrderByWithRelationInputObjectSchema } from './objects/technicalActionCatalogOrderByWithRelationInput.schema';
import { technicalActionCatalogWhereInputObjectSchema as technicalActionCatalogWhereInputObjectSchema } from './objects/technicalActionCatalogWhereInput.schema';
import { technicalActionCatalogWhereUniqueInputObjectSchema as technicalActionCatalogWhereUniqueInputObjectSchema } from './objects/technicalActionCatalogWhereUniqueInput.schema';
import { TechnicalActionCatalogCountAggregateInputObjectSchema as TechnicalActionCatalogCountAggregateInputObjectSchema } from './objects/TechnicalActionCatalogCountAggregateInput.schema';

export const technicalActionCatalogCountSchema: z.ZodType<Prisma.technicalActionCatalogCountArgs> = z.object({ orderBy: z.union([technicalActionCatalogOrderByWithRelationInputObjectSchema, technicalActionCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalActionCatalogWhereInputObjectSchema.optional(), cursor: technicalActionCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), TechnicalActionCatalogCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.technicalActionCatalogCountArgs>;

export const technicalActionCatalogCountZodSchema = z.object({ orderBy: z.union([technicalActionCatalogOrderByWithRelationInputObjectSchema, technicalActionCatalogOrderByWithRelationInputObjectSchema.array()]).optional(), where: technicalActionCatalogWhereInputObjectSchema.optional(), cursor: technicalActionCatalogWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), TechnicalActionCatalogCountAggregateInputObjectSchema ]).optional() }).strict();