import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { approvalRequestsOrderByWithRelationInputObjectSchema as approvalRequestsOrderByWithRelationInputObjectSchema } from './objects/approvalRequestsOrderByWithRelationInput.schema';
import { approvalRequestsWhereInputObjectSchema as approvalRequestsWhereInputObjectSchema } from './objects/approvalRequestsWhereInput.schema';
import { approvalRequestsWhereUniqueInputObjectSchema as approvalRequestsWhereUniqueInputObjectSchema } from './objects/approvalRequestsWhereUniqueInput.schema';
import { ApprovalRequestsCountAggregateInputObjectSchema as ApprovalRequestsCountAggregateInputObjectSchema } from './objects/ApprovalRequestsCountAggregateInput.schema';

export const approvalRequestsCountSchema: z.ZodType<Prisma.approvalRequestsCountArgs> = z.object({ orderBy: z.union([approvalRequestsOrderByWithRelationInputObjectSchema, approvalRequestsOrderByWithRelationInputObjectSchema.array()]).optional(), where: approvalRequestsWhereInputObjectSchema.optional(), cursor: approvalRequestsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), ApprovalRequestsCountAggregateInputObjectSchema ]).optional() }).strict() as unknown as z.ZodType<Prisma.approvalRequestsCountArgs>;

export const approvalRequestsCountZodSchema = z.object({ orderBy: z.union([approvalRequestsOrderByWithRelationInputObjectSchema, approvalRequestsOrderByWithRelationInputObjectSchema.array()]).optional(), where: approvalRequestsWhereInputObjectSchema.optional(), cursor: approvalRequestsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), select: z.union([ z.literal(true), ApprovalRequestsCountAggregateInputObjectSchema ]).optional() }).strict();