import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { AcquisitionSpecJobWhereInputObjectSchema as AcquisitionSpecJobWhereInputObjectSchema } from './objects/AcquisitionSpecJobWhereInput.schema';
import { AcquisitionSpecJobOrderByWithAggregationInputObjectSchema as AcquisitionSpecJobOrderByWithAggregationInputObjectSchema } from './objects/AcquisitionSpecJobOrderByWithAggregationInput.schema';
import { AcquisitionSpecJobScalarWhereWithAggregatesInputObjectSchema as AcquisitionSpecJobScalarWhereWithAggregatesInputObjectSchema } from './objects/AcquisitionSpecJobScalarWhereWithAggregatesInput.schema';
import { AcquisitionSpecJobScalarFieldEnumSchema } from './enums/AcquisitionSpecJobScalarFieldEnum.schema';
import { AcquisitionSpecJobCountAggregateInputObjectSchema as AcquisitionSpecJobCountAggregateInputObjectSchema } from './objects/AcquisitionSpecJobCountAggregateInput.schema';
import { AcquisitionSpecJobMinAggregateInputObjectSchema as AcquisitionSpecJobMinAggregateInputObjectSchema } from './objects/AcquisitionSpecJobMinAggregateInput.schema';
import { AcquisitionSpecJobMaxAggregateInputObjectSchema as AcquisitionSpecJobMaxAggregateInputObjectSchema } from './objects/AcquisitionSpecJobMaxAggregateInput.schema';
import { AcquisitionSpecJobAvgAggregateInputObjectSchema as AcquisitionSpecJobAvgAggregateInputObjectSchema } from './objects/AcquisitionSpecJobAvgAggregateInput.schema';
import { AcquisitionSpecJobSumAggregateInputObjectSchema as AcquisitionSpecJobSumAggregateInputObjectSchema } from './objects/AcquisitionSpecJobSumAggregateInput.schema';

export const AcquisitionSpecJobGroupBySchema: z.ZodType<Prisma.AcquisitionSpecJobGroupByArgs> = z.object({ where: AcquisitionSpecJobWhereInputObjectSchema.optional(), orderBy: z.union([AcquisitionSpecJobOrderByWithAggregationInputObjectSchema, AcquisitionSpecJobOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AcquisitionSpecJobScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AcquisitionSpecJobScalarFieldEnumSchema), _count: z.union([ z.literal(true), AcquisitionSpecJobCountAggregateInputObjectSchema ]).optional(), _min: AcquisitionSpecJobMinAggregateInputObjectSchema.optional(), _max: AcquisitionSpecJobMaxAggregateInputObjectSchema.optional(), _avg: AcquisitionSpecJobAvgAggregateInputObjectSchema.optional(), _sum: AcquisitionSpecJobSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AcquisitionSpecJobGroupByArgs>;

export const AcquisitionSpecJobGroupByZodSchema = z.object({ where: AcquisitionSpecJobWhereInputObjectSchema.optional(), orderBy: z.union([AcquisitionSpecJobOrderByWithAggregationInputObjectSchema, AcquisitionSpecJobOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AcquisitionSpecJobScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AcquisitionSpecJobScalarFieldEnumSchema), _count: z.union([ z.literal(true), AcquisitionSpecJobCountAggregateInputObjectSchema ]).optional(), _min: AcquisitionSpecJobMinAggregateInputObjectSchema.optional(), _max: AcquisitionSpecJobMaxAggregateInputObjectSchema.optional(), _avg: AcquisitionSpecJobAvgAggregateInputObjectSchema.optional(), _sum: AcquisitionSpecJobSumAggregateInputObjectSchema.optional() }).strict();