import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalActionCatalogWhereInputObjectSchema as technicalActionCatalogWhereInputObjectSchema } from './objects/technicalActionCatalogWhereInput.schema';
import { technicalActionCatalogOrderByWithAggregationInputObjectSchema as technicalActionCatalogOrderByWithAggregationInputObjectSchema } from './objects/technicalActionCatalogOrderByWithAggregationInput.schema';
import { technicalActionCatalogScalarWhereWithAggregatesInputObjectSchema as technicalActionCatalogScalarWhereWithAggregatesInputObjectSchema } from './objects/technicalActionCatalogScalarWhereWithAggregatesInput.schema';
import { TechnicalActionCatalogScalarFieldEnumSchema } from './enums/TechnicalActionCatalogScalarFieldEnum.schema';
import { TechnicalActionCatalogCountAggregateInputObjectSchema as TechnicalActionCatalogCountAggregateInputObjectSchema } from './objects/TechnicalActionCatalogCountAggregateInput.schema';
import { TechnicalActionCatalogMinAggregateInputObjectSchema as TechnicalActionCatalogMinAggregateInputObjectSchema } from './objects/TechnicalActionCatalogMinAggregateInput.schema';
import { TechnicalActionCatalogMaxAggregateInputObjectSchema as TechnicalActionCatalogMaxAggregateInputObjectSchema } from './objects/TechnicalActionCatalogMaxAggregateInput.schema';
import { TechnicalActionCatalogAvgAggregateInputObjectSchema as TechnicalActionCatalogAvgAggregateInputObjectSchema } from './objects/TechnicalActionCatalogAvgAggregateInput.schema';
import { TechnicalActionCatalogSumAggregateInputObjectSchema as TechnicalActionCatalogSumAggregateInputObjectSchema } from './objects/TechnicalActionCatalogSumAggregateInput.schema';

export const technicalActionCatalogGroupBySchema: z.ZodType<Prisma.technicalActionCatalogGroupByArgs> = z.object({ where: technicalActionCatalogWhereInputObjectSchema.optional(), orderBy: z.union([technicalActionCatalogOrderByWithAggregationInputObjectSchema, technicalActionCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: technicalActionCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalActionCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalActionCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalActionCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalActionCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalActionCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalActionCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.technicalActionCatalogGroupByArgs>;

export const technicalActionCatalogGroupByZodSchema = z.object({ where: technicalActionCatalogWhereInputObjectSchema.optional(), orderBy: z.union([technicalActionCatalogOrderByWithAggregationInputObjectSchema, technicalActionCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: technicalActionCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalActionCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalActionCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalActionCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalActionCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalActionCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalActionCatalogSumAggregateInputObjectSchema.optional() }).strict();