import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { maintenanceLogsWhereInputObjectSchema as maintenanceLogsWhereInputObjectSchema } from './objects/maintenanceLogsWhereInput.schema';
import { maintenanceLogsOrderByWithAggregationInputObjectSchema as maintenanceLogsOrderByWithAggregationInputObjectSchema } from './objects/maintenanceLogsOrderByWithAggregationInput.schema';
import { maintenanceLogsScalarWhereWithAggregatesInputObjectSchema as maintenanceLogsScalarWhereWithAggregatesInputObjectSchema } from './objects/maintenanceLogsScalarWhereWithAggregatesInput.schema';
import { MaintenanceLogsScalarFieldEnumSchema } from './enums/MaintenanceLogsScalarFieldEnum.schema';
import { MaintenanceLogsCountAggregateInputObjectSchema as MaintenanceLogsCountAggregateInputObjectSchema } from './objects/MaintenanceLogsCountAggregateInput.schema';
import { MaintenanceLogsMinAggregateInputObjectSchema as MaintenanceLogsMinAggregateInputObjectSchema } from './objects/MaintenanceLogsMinAggregateInput.schema';
import { MaintenanceLogsMaxAggregateInputObjectSchema as MaintenanceLogsMaxAggregateInputObjectSchema } from './objects/MaintenanceLogsMaxAggregateInput.schema';
import { MaintenanceLogsAvgAggregateInputObjectSchema as MaintenanceLogsAvgAggregateInputObjectSchema } from './objects/MaintenanceLogsAvgAggregateInput.schema';
import { MaintenanceLogsSumAggregateInputObjectSchema as MaintenanceLogsSumAggregateInputObjectSchema } from './objects/MaintenanceLogsSumAggregateInput.schema';

export const maintenanceLogsGroupBySchema: z.ZodType<Prisma.maintenanceLogsGroupByArgs> = z.object({ where: maintenanceLogsWhereInputObjectSchema.optional(), orderBy: z.union([maintenanceLogsOrderByWithAggregationInputObjectSchema, maintenanceLogsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: maintenanceLogsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MaintenanceLogsScalarFieldEnumSchema), _count: z.union([ z.literal(true), MaintenanceLogsCountAggregateInputObjectSchema ]).optional(), _min: MaintenanceLogsMinAggregateInputObjectSchema.optional(), _max: MaintenanceLogsMaxAggregateInputObjectSchema.optional(), _avg: MaintenanceLogsAvgAggregateInputObjectSchema.optional(), _sum: MaintenanceLogsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.maintenanceLogsGroupByArgs>;

export const maintenanceLogsGroupByZodSchema = z.object({ where: maintenanceLogsWhereInputObjectSchema.optional(), orderBy: z.union([maintenanceLogsOrderByWithAggregationInputObjectSchema, maintenanceLogsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: maintenanceLogsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MaintenanceLogsScalarFieldEnumSchema), _count: z.union([ z.literal(true), MaintenanceLogsCountAggregateInputObjectSchema ]).optional(), _min: MaintenanceLogsMinAggregateInputObjectSchema.optional(), _max: MaintenanceLogsMaxAggregateInputObjectSchema.optional(), _avg: MaintenanceLogsAvgAggregateInputObjectSchema.optional(), _sum: MaintenanceLogsSumAggregateInputObjectSchema.optional() }).strict();