import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MechanicalPartCatalogWhereInputObjectSchema as MechanicalPartCatalogWhereInputObjectSchema } from './objects/MechanicalPartCatalogWhereInput.schema';
import { MechanicalPartCatalogOrderByWithAggregationInputObjectSchema as MechanicalPartCatalogOrderByWithAggregationInputObjectSchema } from './objects/MechanicalPartCatalogOrderByWithAggregationInput.schema';
import { MechanicalPartCatalogScalarWhereWithAggregatesInputObjectSchema as MechanicalPartCatalogScalarWhereWithAggregatesInputObjectSchema } from './objects/MechanicalPartCatalogScalarWhereWithAggregatesInput.schema';
import { MechanicalPartCatalogScalarFieldEnumSchema } from './enums/MechanicalPartCatalogScalarFieldEnum.schema';
import { MechanicalPartCatalogCountAggregateInputObjectSchema as MechanicalPartCatalogCountAggregateInputObjectSchema } from './objects/MechanicalPartCatalogCountAggregateInput.schema';
import { MechanicalPartCatalogMinAggregateInputObjectSchema as MechanicalPartCatalogMinAggregateInputObjectSchema } from './objects/MechanicalPartCatalogMinAggregateInput.schema';
import { MechanicalPartCatalogMaxAggregateInputObjectSchema as MechanicalPartCatalogMaxAggregateInputObjectSchema } from './objects/MechanicalPartCatalogMaxAggregateInput.schema';
import { MechanicalPartCatalogAvgAggregateInputObjectSchema as MechanicalPartCatalogAvgAggregateInputObjectSchema } from './objects/MechanicalPartCatalogAvgAggregateInput.schema';
import { MechanicalPartCatalogSumAggregateInputObjectSchema as MechanicalPartCatalogSumAggregateInputObjectSchema } from './objects/MechanicalPartCatalogSumAggregateInput.schema';

export const MechanicalPartCatalogGroupBySchema: z.ZodType<Prisma.MechanicalPartCatalogGroupByArgs> = z.object({ where: MechanicalPartCatalogWhereInputObjectSchema.optional(), orderBy: z.union([MechanicalPartCatalogOrderByWithAggregationInputObjectSchema, MechanicalPartCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MechanicalPartCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MechanicalPartCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), MechanicalPartCatalogCountAggregateInputObjectSchema ]).optional(), _min: MechanicalPartCatalogMinAggregateInputObjectSchema.optional(), _max: MechanicalPartCatalogMaxAggregateInputObjectSchema.optional(), _avg: MechanicalPartCatalogAvgAggregateInputObjectSchema.optional(), _sum: MechanicalPartCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MechanicalPartCatalogGroupByArgs>;

export const MechanicalPartCatalogGroupByZodSchema = z.object({ where: MechanicalPartCatalogWhereInputObjectSchema.optional(), orderBy: z.union([MechanicalPartCatalogOrderByWithAggregationInputObjectSchema, MechanicalPartCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: MechanicalPartCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(MechanicalPartCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), MechanicalPartCatalogCountAggregateInputObjectSchema ]).optional(), _min: MechanicalPartCatalogMinAggregateInputObjectSchema.optional(), _max: MechanicalPartCatalogMaxAggregateInputObjectSchema.optional(), _avg: MechanicalPartCatalogAvgAggregateInputObjectSchema.optional(), _sum: MechanicalPartCatalogSumAggregateInputObjectSchema.optional() }).strict();