import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { system_job_run_logWhereInputObjectSchema as system_job_run_logWhereInputObjectSchema } from './objects/system_job_run_logWhereInput.schema';
import { system_job_run_logOrderByWithAggregationInputObjectSchema as system_job_run_logOrderByWithAggregationInputObjectSchema } from './objects/system_job_run_logOrderByWithAggregationInput.schema';
import { system_job_run_logScalarWhereWithAggregatesInputObjectSchema as system_job_run_logScalarWhereWithAggregatesInputObjectSchema } from './objects/system_job_run_logScalarWhereWithAggregatesInput.schema';
import { SystemJobRunLogScalarFieldEnumSchema } from './enums/SystemJobRunLogScalarFieldEnum.schema';
import { System_job_run_logCountAggregateInputObjectSchema as System_job_run_logCountAggregateInputObjectSchema } from './objects/System_job_run_logCountAggregateInput.schema';
import { System_job_run_logMinAggregateInputObjectSchema as System_job_run_logMinAggregateInputObjectSchema } from './objects/System_job_run_logMinAggregateInput.schema';
import { System_job_run_logMaxAggregateInputObjectSchema as System_job_run_logMaxAggregateInputObjectSchema } from './objects/System_job_run_logMaxAggregateInput.schema';
import { System_job_run_logAvgAggregateInputObjectSchema as System_job_run_logAvgAggregateInputObjectSchema } from './objects/System_job_run_logAvgAggregateInput.schema';
import { System_job_run_logSumAggregateInputObjectSchema as System_job_run_logSumAggregateInputObjectSchema } from './objects/System_job_run_logSumAggregateInput.schema';

export const system_job_run_logGroupBySchema: z.ZodType<Prisma.system_job_run_logGroupByArgs> = z.object({ where: system_job_run_logWhereInputObjectSchema.optional(), orderBy: z.union([system_job_run_logOrderByWithAggregationInputObjectSchema, system_job_run_logOrderByWithAggregationInputObjectSchema.array()]).optional(), having: system_job_run_logScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SystemJobRunLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), System_job_run_logCountAggregateInputObjectSchema ]).optional(), _min: System_job_run_logMinAggregateInputObjectSchema.optional(), _max: System_job_run_logMaxAggregateInputObjectSchema.optional(), _avg: System_job_run_logAvgAggregateInputObjectSchema.optional(), _sum: System_job_run_logSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.system_job_run_logGroupByArgs>;

export const system_job_run_logGroupByZodSchema = z.object({ where: system_job_run_logWhereInputObjectSchema.optional(), orderBy: z.union([system_job_run_logOrderByWithAggregationInputObjectSchema, system_job_run_logOrderByWithAggregationInputObjectSchema.array()]).optional(), having: system_job_run_logScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SystemJobRunLogScalarFieldEnumSchema), _count: z.union([ z.literal(true), System_job_run_logCountAggregateInputObjectSchema ]).optional(), _min: System_job_run_logMinAggregateInputObjectSchema.optional(), _max: System_job_run_logMaxAggregateInputObjectSchema.optional(), _avg: System_job_run_logAvgAggregateInputObjectSchema.optional(), _sum: System_job_run_logSumAggregateInputObjectSchema.optional() }).strict();