import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TechnicalIssueWhereInputObjectSchema as TechnicalIssueWhereInputObjectSchema } from './objects/TechnicalIssueWhereInput.schema';
import { TechnicalIssueOrderByWithAggregationInputObjectSchema as TechnicalIssueOrderByWithAggregationInputObjectSchema } from './objects/TechnicalIssueOrderByWithAggregationInput.schema';
import { TechnicalIssueScalarWhereWithAggregatesInputObjectSchema as TechnicalIssueScalarWhereWithAggregatesInputObjectSchema } from './objects/TechnicalIssueScalarWhereWithAggregatesInput.schema';
import { TechnicalIssueScalarFieldEnumSchema } from './enums/TechnicalIssueScalarFieldEnum.schema';
import { TechnicalIssueCountAggregateInputObjectSchema as TechnicalIssueCountAggregateInputObjectSchema } from './objects/TechnicalIssueCountAggregateInput.schema';
import { TechnicalIssueMinAggregateInputObjectSchema as TechnicalIssueMinAggregateInputObjectSchema } from './objects/TechnicalIssueMinAggregateInput.schema';
import { TechnicalIssueMaxAggregateInputObjectSchema as TechnicalIssueMaxAggregateInputObjectSchema } from './objects/TechnicalIssueMaxAggregateInput.schema';
import { TechnicalIssueAvgAggregateInputObjectSchema as TechnicalIssueAvgAggregateInputObjectSchema } from './objects/TechnicalIssueAvgAggregateInput.schema';
import { TechnicalIssueSumAggregateInputObjectSchema as TechnicalIssueSumAggregateInputObjectSchema } from './objects/TechnicalIssueSumAggregateInput.schema';

export const TechnicalIssueGroupBySchema: z.ZodType<Prisma.TechnicalIssueGroupByArgs> = z.object({ where: TechnicalIssueWhereInputObjectSchema.optional(), orderBy: z.union([TechnicalIssueOrderByWithAggregationInputObjectSchema, TechnicalIssueOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TechnicalIssueScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalIssueScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalIssueCountAggregateInputObjectSchema ]).optional(), _min: TechnicalIssueMinAggregateInputObjectSchema.optional(), _max: TechnicalIssueMaxAggregateInputObjectSchema.optional(), _avg: TechnicalIssueAvgAggregateInputObjectSchema.optional(), _sum: TechnicalIssueSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TechnicalIssueGroupByArgs>;

export const TechnicalIssueGroupByZodSchema = z.object({ where: TechnicalIssueWhereInputObjectSchema.optional(), orderBy: z.union([TechnicalIssueOrderByWithAggregationInputObjectSchema, TechnicalIssueOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TechnicalIssueScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalIssueScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalIssueCountAggregateInputObjectSchema ]).optional(), _min: TechnicalIssueMinAggregateInputObjectSchema.optional(), _max: TechnicalIssueMaxAggregateInputObjectSchema.optional(), _avg: TechnicalIssueAvgAggregateInputObjectSchema.optional(), _sum: TechnicalIssueSumAggregateInputObjectSchema.optional() }).strict();