import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { system_job_controlWhereInputObjectSchema as system_job_controlWhereInputObjectSchema } from './objects/system_job_controlWhereInput.schema';
import { system_job_controlOrderByWithAggregationInputObjectSchema as system_job_controlOrderByWithAggregationInputObjectSchema } from './objects/system_job_controlOrderByWithAggregationInput.schema';
import { system_job_controlScalarWhereWithAggregatesInputObjectSchema as system_job_controlScalarWhereWithAggregatesInputObjectSchema } from './objects/system_job_controlScalarWhereWithAggregatesInput.schema';
import { SystemJobControlScalarFieldEnumSchema } from './enums/SystemJobControlScalarFieldEnum.schema';
import { System_job_controlCountAggregateInputObjectSchema as System_job_controlCountAggregateInputObjectSchema } from './objects/System_job_controlCountAggregateInput.schema';
import { System_job_controlMinAggregateInputObjectSchema as System_job_controlMinAggregateInputObjectSchema } from './objects/System_job_controlMinAggregateInput.schema';
import { System_job_controlMaxAggregateInputObjectSchema as System_job_controlMaxAggregateInputObjectSchema } from './objects/System_job_controlMaxAggregateInput.schema';
import { System_job_controlAvgAggregateInputObjectSchema as System_job_controlAvgAggregateInputObjectSchema } from './objects/System_job_controlAvgAggregateInput.schema';
import { System_job_controlSumAggregateInputObjectSchema as System_job_controlSumAggregateInputObjectSchema } from './objects/System_job_controlSumAggregateInput.schema';

export const system_job_controlGroupBySchema: z.ZodType<Prisma.system_job_controlGroupByArgs> = z.object({ where: system_job_controlWhereInputObjectSchema.optional(), orderBy: z.union([system_job_controlOrderByWithAggregationInputObjectSchema, system_job_controlOrderByWithAggregationInputObjectSchema.array()]).optional(), having: system_job_controlScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SystemJobControlScalarFieldEnumSchema), _count: z.union([ z.literal(true), System_job_controlCountAggregateInputObjectSchema ]).optional(), _min: System_job_controlMinAggregateInputObjectSchema.optional(), _max: System_job_controlMaxAggregateInputObjectSchema.optional(), _avg: System_job_controlAvgAggregateInputObjectSchema.optional(), _sum: System_job_controlSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.system_job_controlGroupByArgs>;

export const system_job_controlGroupByZodSchema = z.object({ where: system_job_controlWhereInputObjectSchema.optional(), orderBy: z.union([system_job_controlOrderByWithAggregationInputObjectSchema, system_job_controlOrderByWithAggregationInputObjectSchema.array()]).optional(), having: system_job_controlScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SystemJobControlScalarFieldEnumSchema), _count: z.union([ z.literal(true), System_job_controlCountAggregateInputObjectSchema ]).optional(), _min: System_job_controlMinAggregateInputObjectSchema.optional(), _max: System_job_controlMaxAggregateInputObjectSchema.optional(), _avg: System_job_controlAvgAggregateInputObjectSchema.optional(), _sum: System_job_controlSumAggregateInputObjectSchema.optional() }).strict();