import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalAssessmentsWhereInputObjectSchema as technicalAssessmentsWhereInputObjectSchema } from './objects/technicalAssessmentsWhereInput.schema';
import { technicalAssessmentsOrderByWithAggregationInputObjectSchema as technicalAssessmentsOrderByWithAggregationInputObjectSchema } from './objects/technicalAssessmentsOrderByWithAggregationInput.schema';
import { technicalAssessmentsScalarWhereWithAggregatesInputObjectSchema as technicalAssessmentsScalarWhereWithAggregatesInputObjectSchema } from './objects/technicalAssessmentsScalarWhereWithAggregatesInput.schema';
import { TechnicalAssessmentsScalarFieldEnumSchema } from './enums/TechnicalAssessmentsScalarFieldEnum.schema';
import { TechnicalAssessmentsCountAggregateInputObjectSchema as TechnicalAssessmentsCountAggregateInputObjectSchema } from './objects/TechnicalAssessmentsCountAggregateInput.schema';
import { TechnicalAssessmentsMinAggregateInputObjectSchema as TechnicalAssessmentsMinAggregateInputObjectSchema } from './objects/TechnicalAssessmentsMinAggregateInput.schema';
import { TechnicalAssessmentsMaxAggregateInputObjectSchema as TechnicalAssessmentsMaxAggregateInputObjectSchema } from './objects/TechnicalAssessmentsMaxAggregateInput.schema';
import { TechnicalAssessmentsAvgAggregateInputObjectSchema as TechnicalAssessmentsAvgAggregateInputObjectSchema } from './objects/TechnicalAssessmentsAvgAggregateInput.schema';
import { TechnicalAssessmentsSumAggregateInputObjectSchema as TechnicalAssessmentsSumAggregateInputObjectSchema } from './objects/TechnicalAssessmentsSumAggregateInput.schema';

export const technicalAssessmentsGroupBySchema: z.ZodType<Prisma.technicalAssessmentsGroupByArgs> = z.object({ where: technicalAssessmentsWhereInputObjectSchema.optional(), orderBy: z.union([technicalAssessmentsOrderByWithAggregationInputObjectSchema, technicalAssessmentsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: technicalAssessmentsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalAssessmentsScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalAssessmentsCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAssessmentsMinAggregateInputObjectSchema.optional(), _max: TechnicalAssessmentsMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAssessmentsAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAssessmentsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.technicalAssessmentsGroupByArgs>;

export const technicalAssessmentsGroupByZodSchema = z.object({ where: technicalAssessmentsWhereInputObjectSchema.optional(), orderBy: z.union([technicalAssessmentsOrderByWithAggregationInputObjectSchema, technicalAssessmentsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: technicalAssessmentsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalAssessmentsScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalAssessmentsCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAssessmentsMinAggregateInputObjectSchema.optional(), _max: TechnicalAssessmentsMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAssessmentsAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAssessmentsSumAggregateInputObjectSchema.optional() }).strict();