import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalPartCatalogWhereInputObjectSchema as technicalPartCatalogWhereInputObjectSchema } from './objects/technicalPartCatalogWhereInput.schema';
import { technicalPartCatalogOrderByWithAggregationInputObjectSchema as technicalPartCatalogOrderByWithAggregationInputObjectSchema } from './objects/technicalPartCatalogOrderByWithAggregationInput.schema';
import { technicalPartCatalogScalarWhereWithAggregatesInputObjectSchema as technicalPartCatalogScalarWhereWithAggregatesInputObjectSchema } from './objects/technicalPartCatalogScalarWhereWithAggregatesInput.schema';
import { TechnicalPartCatalogScalarFieldEnumSchema } from './enums/TechnicalPartCatalogScalarFieldEnum.schema';
import { TechnicalPartCatalogCountAggregateInputObjectSchema as TechnicalPartCatalogCountAggregateInputObjectSchema } from './objects/TechnicalPartCatalogCountAggregateInput.schema';
import { TechnicalPartCatalogMinAggregateInputObjectSchema as TechnicalPartCatalogMinAggregateInputObjectSchema } from './objects/TechnicalPartCatalogMinAggregateInput.schema';
import { TechnicalPartCatalogMaxAggregateInputObjectSchema as TechnicalPartCatalogMaxAggregateInputObjectSchema } from './objects/TechnicalPartCatalogMaxAggregateInput.schema';
import { TechnicalPartCatalogAvgAggregateInputObjectSchema as TechnicalPartCatalogAvgAggregateInputObjectSchema } from './objects/TechnicalPartCatalogAvgAggregateInput.schema';
import { TechnicalPartCatalogSumAggregateInputObjectSchema as TechnicalPartCatalogSumAggregateInputObjectSchema } from './objects/TechnicalPartCatalogSumAggregateInput.schema';

export const technicalPartCatalogGroupBySchema: z.ZodType<Prisma.technicalPartCatalogGroupByArgs> = z.object({ where: technicalPartCatalogWhereInputObjectSchema.optional(), orderBy: z.union([technicalPartCatalogOrderByWithAggregationInputObjectSchema, technicalPartCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: technicalPartCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalPartCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalPartCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalPartCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalPartCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalPartCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalPartCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.technicalPartCatalogGroupByArgs>;

export const technicalPartCatalogGroupByZodSchema = z.object({ where: technicalPartCatalogWhereInputObjectSchema.optional(), orderBy: z.union([technicalPartCatalogOrderByWithAggregationInputObjectSchema, technicalPartCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: technicalPartCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalPartCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalPartCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalPartCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalPartCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalPartCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalPartCatalogSumAggregateInputObjectSchema.optional() }).strict();