import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { TechnicalAssessmentWhereInputObjectSchema as TechnicalAssessmentWhereInputObjectSchema } from './objects/TechnicalAssessmentWhereInput.schema';
import { TechnicalAssessmentOrderByWithAggregationInputObjectSchema as TechnicalAssessmentOrderByWithAggregationInputObjectSchema } from './objects/TechnicalAssessmentOrderByWithAggregationInput.schema';
import { TechnicalAssessmentScalarWhereWithAggregatesInputObjectSchema as TechnicalAssessmentScalarWhereWithAggregatesInputObjectSchema } from './objects/TechnicalAssessmentScalarWhereWithAggregatesInput.schema';
import { TechnicalAssessmentScalarFieldEnumSchema } from './enums/TechnicalAssessmentScalarFieldEnum.schema';
import { TechnicalAssessmentCountAggregateInputObjectSchema as TechnicalAssessmentCountAggregateInputObjectSchema } from './objects/TechnicalAssessmentCountAggregateInput.schema';
import { TechnicalAssessmentMinAggregateInputObjectSchema as TechnicalAssessmentMinAggregateInputObjectSchema } from './objects/TechnicalAssessmentMinAggregateInput.schema';
import { TechnicalAssessmentMaxAggregateInputObjectSchema as TechnicalAssessmentMaxAggregateInputObjectSchema } from './objects/TechnicalAssessmentMaxAggregateInput.schema';
import { TechnicalAssessmentAvgAggregateInputObjectSchema as TechnicalAssessmentAvgAggregateInputObjectSchema } from './objects/TechnicalAssessmentAvgAggregateInput.schema';
import { TechnicalAssessmentSumAggregateInputObjectSchema as TechnicalAssessmentSumAggregateInputObjectSchema } from './objects/TechnicalAssessmentSumAggregateInput.schema';

export const TechnicalAssessmentGroupBySchema: z.ZodType<Prisma.TechnicalAssessmentGroupByArgs> = z.object({ where: TechnicalAssessmentWhereInputObjectSchema.optional(), orderBy: z.union([TechnicalAssessmentOrderByWithAggregationInputObjectSchema, TechnicalAssessmentOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TechnicalAssessmentScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalAssessmentScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalAssessmentCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAssessmentMinAggregateInputObjectSchema.optional(), _max: TechnicalAssessmentMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAssessmentAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAssessmentSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.TechnicalAssessmentGroupByArgs>;

export const TechnicalAssessmentGroupByZodSchema = z.object({ where: TechnicalAssessmentWhereInputObjectSchema.optional(), orderBy: z.union([TechnicalAssessmentOrderByWithAggregationInputObjectSchema, TechnicalAssessmentOrderByWithAggregationInputObjectSchema.array()]).optional(), having: TechnicalAssessmentScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalAssessmentScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalAssessmentCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAssessmentMinAggregateInputObjectSchema.optional(), _max: TechnicalAssessmentMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAssessmentAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAssessmentSumAggregateInputObjectSchema.optional() }).strict();