import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { technicalAppearanceIssueCatalogWhereInputObjectSchema as technicalAppearanceIssueCatalogWhereInputObjectSchema } from './objects/technicalAppearanceIssueCatalogWhereInput.schema';
import { technicalAppearanceIssueCatalogOrderByWithAggregationInputObjectSchema as technicalAppearanceIssueCatalogOrderByWithAggregationInputObjectSchema } from './objects/technicalAppearanceIssueCatalogOrderByWithAggregationInput.schema';
import { technicalAppearanceIssueCatalogScalarWhereWithAggregatesInputObjectSchema as technicalAppearanceIssueCatalogScalarWhereWithAggregatesInputObjectSchema } from './objects/technicalAppearanceIssueCatalogScalarWhereWithAggregatesInput.schema';
import { TechnicalAppearanceIssueCatalogScalarFieldEnumSchema } from './enums/TechnicalAppearanceIssueCatalogScalarFieldEnum.schema';
import { TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogCountAggregateInput.schema';
import { TechnicalAppearanceIssueCatalogMinAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogMinAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogMinAggregateInput.schema';
import { TechnicalAppearanceIssueCatalogMaxAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogMaxAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogMaxAggregateInput.schema';
import { TechnicalAppearanceIssueCatalogAvgAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogAvgAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogAvgAggregateInput.schema';
import { TechnicalAppearanceIssueCatalogSumAggregateInputObjectSchema as TechnicalAppearanceIssueCatalogSumAggregateInputObjectSchema } from './objects/TechnicalAppearanceIssueCatalogSumAggregateInput.schema';

export const technicalAppearanceIssueCatalogGroupBySchema: z.ZodType<Prisma.technicalAppearanceIssueCatalogGroupByArgs> = z.object({ where: technicalAppearanceIssueCatalogWhereInputObjectSchema.optional(), orderBy: z.union([technicalAppearanceIssueCatalogOrderByWithAggregationInputObjectSchema, technicalAppearanceIssueCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: technicalAppearanceIssueCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalAppearanceIssueCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAppearanceIssueCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalAppearanceIssueCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAppearanceIssueCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAppearanceIssueCatalogSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.technicalAppearanceIssueCatalogGroupByArgs>;

export const technicalAppearanceIssueCatalogGroupByZodSchema = z.object({ where: technicalAppearanceIssueCatalogWhereInputObjectSchema.optional(), orderBy: z.union([technicalAppearanceIssueCatalogOrderByWithAggregationInputObjectSchema, technicalAppearanceIssueCatalogOrderByWithAggregationInputObjectSchema.array()]).optional(), having: technicalAppearanceIssueCatalogScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(TechnicalAppearanceIssueCatalogScalarFieldEnumSchema), _count: z.union([ z.literal(true), TechnicalAppearanceIssueCatalogCountAggregateInputObjectSchema ]).optional(), _min: TechnicalAppearanceIssueCatalogMinAggregateInputObjectSchema.optional(), _max: TechnicalAppearanceIssueCatalogMaxAggregateInputObjectSchema.optional(), _avg: TechnicalAppearanceIssueCatalogAvgAggregateInputObjectSchema.optional(), _sum: TechnicalAppearanceIssueCatalogSumAggregateInputObjectSchema.optional() }).strict();